name: main

on:
  push:
    branches:
      - main
jobs:
  run-coupons: #任務名
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Setup Node.js
        uses: action/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependency
        run: |
          npm install
          node ./coupons.js #要運行的事情
